### PR TITLE
Issue64: Add active storage to have profile photo + images 

### PR DESCRIPTION
**Pull request by swei0810**
The profile page will now display the profile photo and additional images. 
Upload photo button will only appear if you are the current_user & have less than 13 images already uploaded.

This does NOT take care of uploading the photos itself - this requires work done on editing the profile page first (which I'm having trouble with because of devise & password requirement - will work on this now) so this only displays photos that are already provided on the seed file.

### CODE REVIEW

**Comment by brittchin99** [comment]
Looks pretty good - how are the images being stored? In a table? I'm thinking how many will be displayed in each row if the screen size shrinks, etc. I think tables can resize so should be okay? We can also consider using things like cards to store the images so people can still click on them.

Another comment, they should be able to add 13 pics but also remove them to add new ones. If it's not too hard to implement they should also be able to rearrange the order - not sure how that would work, maybe like storing the photos in a list and when they drag it move the position in the list. Not for this pull request ofc.

**Review by emilycg — APPROVED** [review]
Everything looks good. Umm I don't know if we want to show empty boxes if no photos are uploaded. Does uploading a profile picture work?

**Comment by swei0810** [comment]
Images are being stored in a separate active storage table. I haven't checked what it looks like with different screen sizes so I'll check that. Not 100% sure but I think I can make it be clickable and show a bigger version too. 

I'll read more on how to rearrange them with drag on the next request!

For empty boxes - ill make the change based on our discussion over slack. 

Uploading a profile picture does not work for this request - i'll have to deal with updating the profile itself first to be able to upload photos because of devise's password requirements.

**Comment by brittchin99** [comment]
> Images are being stored in a separate active storage table. I haven't checked what it looks like with different screen sizes so I'll check that. Not 100% sure but I think I can make it be clickable and show a bigger version too.
> 
> I'll read more on how to rearrange them with drag on the next request!
> 
> For empty boxes - ill make the change based on our discussion over slack.
> 
> Uploading a profile picture does not work for this request - i'll have to deal with updating the profile itself first to be able to upload photos because of devise's password requirements.

Sounds good! Nice job Si. Can also check out these references:
https://medium.com/@anaharris/how-to-add-image-upload-functionality-to-your-rails-app-9f7fc3f3d042

https://www.microverse.org/blog/how-to-build-an-image-upload-feature-with-rails-and-active-storage

https://github.com/LearnCodeWeb/Dropzone-images-with-reorder

https://www.geeksforgeeks.org/how-to-create-a-drag-and-drop-feature-for-reordering-the-images-using-html-css-and-jqueryui/

https://www.codexworld.com/drag-drop-images-reorder-using-jquery-ajax-php-mysql/

**Pull request merged**
