### PR TITLE
adding account model

### PR DESCRIPTION
**Pull request by brittchin99**
Added Account model with the following attributes:
first_name: string
last_name: string
password: string
pronouns: string
class_year: integer
majors: string
minors: string
interests: string

We might have more attributes later. I also wanted majors, minors, and interests to be arrays of strings, not sure how that would work.

### CODE REVIEW

**Review by ntp99 — COMMENTED** [review]
The model fields look good to me and the create account form showed up. Submitting the form causes an error for now so let's work on finishing setting up the account and then add some tests. Maybe we should add some validations to the account too.

**Comment by brittchin99** [comment]
> The model fields look good to me and the create account form showed up. Submitting the form causes an error for now so let's work on finishing setting up the account and then add some tests. Maybe we should add some validations to the account too.

Currently form isn't set up/attached to anything, I'm still working on that right now.

**Comment by swei0810** [comment]
For class_year, do we want to restrict it to current students? If so, it would make sense to give it a range. 
In terms of majors, minors, and interests - maybe we can just ask the users to separate them with a comma and we can parse it on our end when we're using them later on. 
Also, do we have a separate username? Or are we using first_name as that?

**Comment by brittchin99** [comment]
> For class_year, do we want to restrict it to current students? If so, it would make sense to give it a range.
> In terms of majors, minors, and interests - maybe we can just ask the users to separate them with a comma and we can parse it on our end when we're using them later on.
> Also, do we have a separate username? Or are we using first_name as that?

On the create account form, the class year selection will be radio buttons or a dropdown to restrict to current class years. We will have to do validation on the controller side to make sure that the year is valid still. For major(s)/minor(s) we have the list of 56 that we can pull on the backend to populate a dropdown and again handle validation in the controller or on the front end. They don't have a username since they just log in with their email and password.

**Pull request merged**
