### PR TITLE
Upload images successfully

### PR DESCRIPTION
**Pull request by swei0810**
Can update profile photo and upload additional photos on profile page

### CODE REVIEW

**Comment by brittchin99** [comment]
I got this error when I tried to upload a photo:
Screen Shot 2020-11-30 at 2 00 52 PM

**Comment by brittchin99** [comment]
Also I uploaded a profile photo but after refreshing the page it disappeared?

**Comment by swei0810** [comment]
@brittchin99 Fixed the issues you mentioned above. 

- Photos table now has a drag & drop feature so that a user can move the photos around. The change will automatically be saved and stays even if refreshed. 
- I'm still looking into deleting photos. It seems that it might require it to be in a separate model so I'll work on that on a separate branch.

**Review by ntp99 — COMMENTED** [review]
This should be a quick fix but if the user clicks on the update profile button on the photo without uploading any photo, there will be an error. Otherwise this is working.

**Comment by swei0810** [comment]
@ntp99 Thanks for pointing that out! Just fixed it!

**Review by ntp99 — APPROVED** [review]
Images work now! I don't know if this problem could be solved by merging with main but seems like if you click on the account dropdown, the dropdown menu (My Profile and Log Out) will cover the account name. Can you check it when you merge to main?

**Comment by brittchin99** [comment]
You can merge with main, but I was wondering if you know how to have it so the image fills the square proportionally and doesn't stretch (see attachment). It would be nice when the upload they can drag the square to crop properly, but if not filling proportionally is good!
Screen Shot 2020-12-09 at 3 38 59 PM

**Comment by brittchin99** [comment]
> Images work now! I don't know if this problem could be solved by merging with main but seems like if you click on the account dropdown, the dropdown menu (My Profile and Log Out) will cover the account name. Can you check it when you merge to main?

I don't think this should be an issue after merging? It looks fine in main, and Si's branch has a really old version of the bootstrap.

**Pull request merged**
