### PR TITLE
Added two-way connection

### PR DESCRIPTION
**Pull request by ntp99**
When a user sends a friend request, the receiver has to accept it to create a connection

### CODE REVIEW

**Review by brittchin99 — APPROVED** [review]
Everything looks good and seems to work! Quick question - will users be notified when someone accepts their request?

**Comment by brittchin99** [comment]
Also, I think the request and deny buttons should also appear in the table next to the person's name

**Review by emilycg — APPROVED** [review]
everything looks good!

**Comment by swei0810** [comment]
Looks great to me!

**Pull request merged**
